# Generated by Django 2.2.16 on 2022-12-07 14:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20221206_1644'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_review',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_by_admin',
        ),
        migrations.AddField(
            model_name='user',
            name='created_by',
            field=models.CharField(choices=[('admin', 'Администратор'), ('web', 'Веб'), ('appp', 'Приложение')], default='appp', max_length=50, verbose_name='Источник создания пользователя'),
        ),
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveIntegerField(default=1, error_messages={'validators': 'Поставьте оценку от 1 до 10.'}, help_text='Поставьте оценку', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Оценка произведения'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('title', 'author'), name='unique_review'),
        ),
    ]
